name: sync_test_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
      flutter_riverpod: ^2.3.7
  cloud_firestore: ^5.5.0
  firebase_core: ^3.10.0
  connectivity_plus: ^6.0.4
  drift: ^2.18.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
 